
#define JOB_AVAILABLE 0
#define JOB_UNAVAILABLE_GENERIC 1
#define JOB_UNAVAILABLE_BANNED 2
#define JOB_UNAVAILABLE_PLAYTIME 3
#define JOB_UNAVAILABLE_ACCOUNTAGE 4
#define JOB_UNAVAILABLE_SLOTFULL 5
#define JOB_UNAVAILABLE_GENERATION 6
#define JOB_UNAVAILABLE_MASQUERADE 7
#define JOB_UNAVAILABLE_SPECIES 8
#define JOB_UNAVAILABLE_SPECIES_LIMITED 9
#define JOB_UNAVAILABLE_CLAN 10
#define JOB_UNAVAILABLE_AGE 11
#define JOB_UNAVAILABLE_WHITELISTED 12
#define JOB_UNAVAILABLE_RANK 13
#define JOB_UNAVAILABLE_TRIBE 14
#define JOB_UNAVAILABLE_CHARACTER_AGE 15
#define JOB_UNAVAILABLE_VAMPIRE_AGE 16

#define DEFAULT_RELIGION "Christianity"
#define DEFAULT_DEITY "Space Jesus"
#define DEFAULT_BIBLE "Default Bible Name"
#define DEFAULT_BIBLE_REPLACE(religion) "The Holy Book of [religion]"

#define JOB_DISPLAY_ORDER_DEFAULT 0

#define JOB_DISPLAY_ORDER_CITIZEN 1
#define JOB_DISPLAY_ORDER_SALUBRI 2
#define JOB_DISPLAY_ORDER_LASOMBRA 3
#define JOB_DISPLAY_ORDER_DAUGHTER 4
#define JOB_DISPLAY_ORDER_BAALI 5
#define JOB_DISPLAY_ORDER_TRUJAH 6
#define JOB_DISPLAY_ORDER_KIASYD 7
#define JOB_DISPLAY_ORDER_BANU 8
#define JOB_DISPLAY_ORDER_NAGARAJA 9
#define JOB_DISPLAY_ORDER_PRINCE 10
#define JOB_DISPLAY_ORDER_SHERIFF 11
#define JOB_DISPLAY_ORDER_CLERK 12
#define JOB_DISPLAY_ORDER_HARPY 13
#define JOB_DISPLAY_ORDER_HOUND 14
#define JOB_DISPLAY_ORDER_TOWERWORK 15
#define JOB_DISPLAY_ORDER_BANUPRIM 16
#define JOB_DISPLAY_ORDER_LASOMBRAPRIM 17
#define JOB_DISPLAY_ORDER_MALKAVIAN 18
#define JOB_DISPLAY_ORDER_NOSFERATU 19
#define JOB_DISPLAY_ORDER_TOREADOR 20
#define JOB_DISPLAY_ORDER_VENTRUE 21
#define JOB_DISPLAY_ORDER_PRIEST 22
#define JOB_DISPLAY_ORDER_CLINICS_DIRECTOR 23
#define JOB_DISPLAY_ORDER_DOCTOR 24
#define JOB_DISPLAY_ORDER_GRAVEYARD 25
#define JOB_DISPLAY_ORDER_STREETJAN 26
#define JOB_DISPLAY_ORDER_STRIP 27
#define JOB_DISPLAY_ORDER_TAXI 28
#define JOB_DISPLAY_ORDER_TRIAD_GANGSTER 29
#define JOB_DISPLAY_ORDER_BARKEEPER 30
#define JOB_DISPLAY_ORDER_EMISSARY 31
#define JOB_DISPLAY_ORDER_SWEEPER 32
#define JOB_DISPLAY_ORDER_BRUISER 33
#define JOB_DISPLAY_ORDER_DEALER 34
#define JOB_DISPLAY_ORDER_SUPPLY 35
#define JOB_DISPLAY_ORDER_REGENT 36
#define JOB_DISPLAY_ORDER_ARCHIVIST 37
#define JOB_DISPLAY_ORDER_GARGOYLE 38
#define JOB_DISPLAY_ORDER_GIOVANNI 39
#define JOB_DISPLAY_ORDER_POLICE_CHIEF 40
#define JOB_DISPLAY_ORDER_POLICE 41
#define JOB_DISPLAY_ORDER_POLICE_SERGEANT 42
#define JOB_DISPLAY_ORDER_DISTRICT_ATTORNEY 43
#define JOB_DISPLAY_ORDER_FBI 44
#define JOB_DISPLAY_ORDER_VOIVODE 45
#define JOB_DISPLAY_ORDER_BOGATYR 46
#define JOB_DISPLAY_ORDER_ZADRUGA 47
#define JOB_DISPLAY_ORDER_AMBERGLADE 48
#define JOB_DISPLAY_ORDER_PAINTEDCITY 49
#define JOB_DISPLAY_ORDER_ENDRON 50
#define JOB_DISPLAY_ORDER_SABBATDUCTUS 51
#define JOB_DISPLAY_ORDER_SABBATPACK 52
#define JOB_DISPLAY_ORDER_SABBATPRIEST 53
// #define JOB_DISPLAY_ORDER_INVESTIGATOR 25
// #define JOB_DISPLAY_ORDER_CHAPLAIN 26
/*
#define JOB_DISPLAY_ORDER_ASSISTANT 1
#define JOB_DISPLAY_ORDER_CAPTAIN 2
#define JOB_DISPLAY_ORDER_HEAD_OF_PERSONNEL 3
#define JOB_DISPLAY_ORDER_QUARTERMASTER 4
#define JOB_DISPLAY_ORDER_CARGO_TECHNICIAN 5
#define JOB_DISPLAY_ORDER_SHAFT_MINER 6
#define JOB_DISPLAY_ORDER_BARTENDER 7
#define JOB_DISPLAY_ORDER_COOK 8
#define JOB_DISPLAY_ORDER_BOTANIST 9
#define JOB_DISPLAY_ORDER_JANITOR 10
#define JOB_DISPLAY_ORDER_CLOWN 11
#define JOB_DISPLAY_ORDER_MIME 12
#define JOB_DISPLAY_ORDER_CURATOR 13
#define JOB_DISPLAY_ORDER_LAWYER 14
#define JOB_DISPLAY_ORDER_CHAPLAIN 15
#define JOB_DISPLAY_ORDER_AI 16
#define JOB_DISPLAY_ORDER_CYBORG 17
#define JOB_DISPLAY_ORDER_CHIEF_ENGINEER 18
#define JOB_DISPLAY_ORDER_STATION_ENGINEER 19
#define JOB_DISPLAY_ORDER_ATMOSPHERIC_TECHNICIAN 20
#define JOB_DISPLAY_ORDER_CHIEF_MEDICAL_OFFICER 21
#define JOB_DISPLAY_ORDER_MEDICAL_DOCTOR 22
#define JOB_DISPLAY_ORDER_PARAMEDIC 23
#define JOB_DISPLAY_ORDER_CHEMIST 24
#define JOB_DISPLAY_ORDER_VIROLOGIST 25
#define JOB_DISPLAY_ORDER_PSYCHOLOGIST 26
#define JOB_DISPLAY_ORDER_RESEARCH_DIRECTOR 27
#define JOB_DISPLAY_ORDER_SCIENTIST 28
#define JOB_DISPLAY_ORDER_ROBOTICIST 29
#define JOB_DISPLAY_ORDER_GENETICIST 30
#define JOB_DISPLAY_ORDER_HEAD_OF_SECURITY 31
#define JOB_DISPLAY_ORDER_WARDEN 32
#define JOB_DISPLAY_ORDER_DETECTIVE 33
#define JOB_DISPLAY_ORDER_SECURITY_OFFICER 34
#define JOB_DISPLAY_ORDER_PRISONER 35
*/
